### ISSUE TITLE
HEALTHCHECK Error

### ISSUE THREAD

**Issue by flipkill1985** [docker-home-automation-stack/fhem-docker#5]
Step 69/72 : HEALTHCHECK --interval=20s --timeout=10s --start-period=60s --retries=5 CMD /health-check.sh
Unknown flag: start-period

**Comment by jpawlowski** [comment]
make sure you are using the current Docker version on your host.

**Comment by flipkill1985** [comment]
Docker version 1.13.1, build 6e3bb8e/1.13.1

**Comment by jpawlowski** [comment]
Docker version 17.06 is required as a minimum to run the container.
I am again referring to the pre-build images, see #4.

Also, be reminded that docker-compose is a separate component and needs to be updated separately to allow compatibility with some newer Docker features like start-period:
https://docs.docker.com/compose/install/
